# The start symbol is TOP.

# These two rules are required; choose their weights carefully!
99  TOP  S1
1   TOP  S2

# This is a very, very, very simple grammar to get you started.

1   S1   NP VP
1   S1   NP _VP
1   S1   SN SVP
1   S1   PLN PVP
1   S1   S1 CCP
1   S1   Expl _!
1   S1   Excl _!
1   S1   NP VP
1   S1   NP _VP
1   S1   WhPn _VP?

#Verb Phrases
1   _VP  VP Punc
1   _VP?  VP _?
1   _VP!  VP _!

1   VP   SVP
1   VP   PVP
1   VP   IVP
1   IVP  IPreVBG VBG
1   IVP  IPreVBG _JJ
1   IVP   IPreVBG NP
1   SVP   VerbT NP
1   SVP   VerbT AJJ
1   SVP   SPreVBG VBG
1   SVP   SPreVBG _JJ
1   SVP   SPreVBG NP
1   PVP   PPreVBG _JJ
1   PVP   PPreVBG VBG
1   PVP   PPreVBG NP
1   VP   VBD NP
1   VP   Adv VP
1   VP   PreVBDD VBDD
1   VP   TO VB
1   VP   VerbT
1   VP   MV VBG
1   VP   MV VB
1   VP   FM VBG
1   FM   MV BE

#Noun Phrases
1   Det  SDet

1   NP   Det _NP
1   NP   SDet _SNN
1   NP   Proper
1   NP   SJJ _NP
1   NP   CJJ _NP
1   _NP  Noun
1   _NP  NNS
1   _NP  PrpNS
1   _NP  IPRP
1   _NP  Proper
1   _NP  _NP PP

1   _SNN Noun
1   _SNN Proper
1   _SNN IPRP
1   _PNN NNS
1   _PNN PrpNS
1   SN   _SNN 
1   SN   SMyPn
1   PLN  _PNN
1   PLN  PMyPn

#Prepositions
1   PP   Prep NP

#Conjuctions
1   CCP  CC  VP
1   CCP  SC  VP

#Adjectives
1   _JJ  Det   SJJ
1   _JJ  CJJ
1   _JJ  JJ
1   _JJ  Adv   SJJ
1   AJJ  Det   SJJ
1   AJJ  Adv   JJ

#Negation
1   _NVBG  NOT VBG
1   _NVBDD NOT VBDD
1   _NJJ   NOT _JJ
      
#'s
1   NP   AsN  _NP
1   AsN  SN  AS
      
#counting
1   CNN  SNum _SNN
1   CNN  PNum _PNN

#Pronouns     
1   NP   PosPn _NP
1   VP   SN VB3
1   VP   PLN VB3S

# in case you use S1.gr by itself
1   S2   Misc

# How and where
S _WhAdv VP
_WhAdv how
_WhAdv where
 VP     _PreVBG _NP
_PreVBG is
_PreVBG was
_NP     SMyPn _?
_NP     IPRP _?
_NP     Proper _?
_NP     _the __NP
_the     the
__NP    Noun _?
VP      PreVBGs sNP
PreVBGs were
PreVBGs are
sNP     _the ssNP
ssNP    PrpNS _?

sNP     _the sssNP
sNP     _their sssNP
_their   their
sssNP   NNS _?

VP  _am _Ipn
_am  am
_Ipn I _?

VP _have _NPS
VP _had  _NPG
VP _has  _NPH
_NPG Proper _VBDD
_NPG _the _NPT
_NPG _the _NPU
_NPT Noun _VBDD
_NPT MyPn _VBDD
_NPT SMyPn _VBDD
_NPT IPRP _VBDD
_NPS _the _NPU
_NPU PrpNS _VBDD
_NPU NNS _VBDD
_VBDD VBDD _?
_NPT Noun _VBDD

#where do the/how do they
S _where VP
S _how VP
VP _do NP
NP PMyPnS VB3S
_where where
_how   how 
_do do
PMyPnS they

#WHY
S _why _VPwhy
_VPwhy PreVBG NP
NP _first _last
_first SMyPn _?
_first Proper _?
_first IPRP _?
_last Prep _?
_last JJ _?
_last VBG _?
